/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type PromptVariables__it__0_0_1 = never;
export type PromptConfig__it__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__it__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__it__0_0_1;
  variables: PromptVariables__it__0_0_1;
  content: string;
};
export type Prompt__it = {
  name: 'it';
  slug: 'it';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__it__0_0_1;
  };
};
export type Globals = {};
export type Agency = {
  prompts: {
    it: Prompt__it;
  };
  globals: Globals;
};
